site_name: Cyber Blueprint 2026 – Mini-SIEM
site_url: https://suleohis.github.io/cyber-blueprint-2026
theme:
  name: material
  palette:
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Dashboard: dashboard.md
  - Detection Engine: detector.md
  - Attack Simulation: generate_logs.md
  - Daily Progress: 
      - Month 1: month1/progress.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/suleohis
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/suleohis

repo_url: https://github.com/suleohis/cyber-blueprint-2026
repo_name: suleohis/cyber-blueprint-2026

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist